{"level":"error","message":"Error in Google OAuth strategy: secretOrPrivateKey must have a value","stack":"Error: secretOrPrivateKey must have a value\n    at module.exports [as sign] (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\jsonwebtoken\\sign.js:111:20)\n    at Strategy._verify (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\config\\passport.js:23:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-09T06:59:58.395Z"}
{"level":"error","message":"Authentication error: secretOrPrivateKey must have a value","stack":"Error: secretOrPrivateKey must have a value\n    at module.exports [as sign] (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\jsonwebtoken\\sign.js:111:20)\n    at Strategy._verify (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\config\\passport.js:23:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-09T06:59:58.397Z"}
{"level":"error","message":"Error in Google OAuth strategy: secretOrPrivateKey must have a value","stack":"Error: secretOrPrivateKey must have a value\n    at module.exports [as sign] (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\jsonwebtoken\\sign.js:111:20)\n    at Strategy._verify (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\config\\passport.js:23:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-09T07:00:44.592Z"}
{"level":"error","message":"Authentication error: secretOrPrivateKey must have a value","stack":"Error: secretOrPrivateKey must have a value\n    at module.exports [as sign] (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\jsonwebtoken\\sign.js:111:20)\n    at Strategy._verify (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\config\\passport.js:23:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-09T07:00:44.596Z"}
{"level":"error","message":"Error in Google OAuth strategy: secretOrPrivateKey must have a value","stack":"Error: secretOrPrivateKey must have a value\n    at module.exports [as sign] (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\jsonwebtoken\\sign.js:111:20)\n    at Strategy._verify (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\config\\passport.js:23:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-09T07:00:50.991Z"}
{"level":"error","message":"Authentication error: secretOrPrivateKey must have a value","stack":"Error: secretOrPrivateKey must have a value\n    at module.exports [as sign] (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\jsonwebtoken\\sign.js:111:20)\n    at Strategy._verify (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\config\\passport.js:23:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-09T07:00:50.993Z"}
{"level":"error","message":"Error in Google OAuth strategy: secretOrPrivateKey must have a value","stack":"Error: secretOrPrivateKey must have a value\n    at module.exports [as sign] (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\jsonwebtoken\\sign.js:111:20)\n    at Strategy._verify (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\config\\passport.js:23:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-09T07:01:02.275Z"}
{"level":"error","message":"Authentication error: secretOrPrivateKey must have a value","stack":"Error: secretOrPrivateKey must have a value\n    at module.exports [as sign] (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\jsonwebtoken\\sign.js:111:20)\n    at Strategy._verify (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\config\\passport.js:23:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-09T07:01:02.275Z"}
{"level":"error","message":"Error in Google OAuth strategy: secretOrPrivateKey must have a value","stack":"Error: secretOrPrivateKey must have a value\n    at module.exports [as sign] (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\jsonwebtoken\\sign.js:111:20)\n    at Strategy._verify (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\config\\passport.js:23:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-09T07:01:10.378Z"}
{"level":"error","message":"Authentication error: secretOrPrivateKey must have a value","stack":"Error: secretOrPrivateKey must have a value\n    at module.exports [as sign] (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\jsonwebtoken\\sign.js:111:20)\n    at Strategy._verify (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\config\\passport.js:23:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-09T07:01:10.379Z"}
{"code":"invalid_grant","level":"error","message":"Authentication error: Bad Request","name":"TokenError","stack":"TokenError: Bad Request\n    at OAuth2Strategy.parseErrorResponse (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\passport-oauth2\\lib\\strategy.js:373:12)\n    at OAuth2Strategy._createOAuthError (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\passport-oauth2\\lib\\strategy.js:420:16)\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\passport-oauth2\\lib\\strategy.js:177:45\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\oauth\\lib\\oauth2.js:196:18\n    at passBackControl (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\oauth\\lib\\oauth2.js:132:9)\n    at IncomingMessage.<anonymous> (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\oauth\\lib\\oauth2.js:157:7)\n    at IncomingMessage.emit (node:events:529:35)\n    at endReadableNT (node:internal/streams/readable:1400:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","status":500,"timestamp":"2025-05-09T07:02:24.633Z"}
{"level":"error","message":"Error in Google OAuth strategy: secretOrPrivateKey must have a value","stack":"Error: secretOrPrivateKey must have a value\n    at module.exports [as sign] (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\jsonwebtoken\\sign.js:111:20)\n    at Strategy._verify (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\config\\passport.js:23:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-09T07:02:35.832Z"}
{"level":"error","message":"Authentication error: secretOrPrivateKey must have a value","stack":"Error: secretOrPrivateKey must have a value\n    at module.exports [as sign] (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\jsonwebtoken\\sign.js:111:20)\n    at Strategy._verify (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\config\\passport.js:23:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-09T07:02:35.833Z"}
{"code":11000,"index":0,"keyPattern":{"mobile":1},"keyValue":{"mobile":null},"level":"error","message":"Authentication error: E11000 duplicate key error collection: pg.users index: mobile_1 dup key: { mobile: null }","stack":"MongoServerError: E11000 duplicate key error collection: pg.users index: mobile_1 dup key: { mobile: null }\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongodb\\lib\\operations\\insert.js:50:33\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongodb\\lib\\operations\\command.js:84:64\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-09T07:29:05.393Z"}
{"code":11000,"index":0,"keyPattern":{"mobile":1},"keyValue":{"mobile":null},"level":"error","message":"Authentication error: E11000 duplicate key error collection: pg.users index: mobile_1 dup key: { mobile: null }","stack":"MongoServerError: E11000 duplicate key error collection: pg.users index: mobile_1 dup key: { mobile: null }\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongodb\\lib\\operations\\insert.js:50:33\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongodb\\lib\\operations\\command.js:84:64\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-09T07:29:37.748Z"}
{"code":11000,"index":0,"keyPattern":{"mobile":1},"keyValue":{"mobile":null},"level":"error","message":"Authentication error: E11000 duplicate key error collection: pg.users index: mobile_1 dup key: { mobile: null }","stack":"MongoServerError: E11000 duplicate key error collection: pg.users index: mobile_1 dup key: { mobile: null }\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongodb\\lib\\operations\\insert.js:50:33\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongodb\\lib\\operations\\command.js:84:64\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-09T07:34:47.365Z"}
{"code":11000,"index":0,"keyPattern":{"mobile":1},"keyValue":{"mobile":null},"level":"error","message":"Authentication error: E11000 duplicate key error collection: pg.users index: mobile_1 dup key: { mobile: null }","stack":"MongoServerError: E11000 duplicate key error collection: pg.users index: mobile_1 dup key: { mobile: null }\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongodb\\lib\\operations\\insert.js:50:33\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongodb\\lib\\operations\\command.js:84:64\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-09T14:38:57.200Z"}
{"code":"invalid_grant","level":"error","message":"Authentication error: Bad Request","name":"TokenError","stack":"TokenError: Bad Request\n    at OAuth2Strategy.parseErrorResponse (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\passport-oauth2\\lib\\strategy.js:373:12)\n    at OAuth2Strategy._createOAuthError (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\passport-oauth2\\lib\\strategy.js:420:16)\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\passport-oauth2\\lib\\strategy.js:177:45\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\oauth\\lib\\oauth2.js:196:18\n    at passBackControl (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\oauth\\lib\\oauth2.js:132:9)\n    at IncomingMessage.<anonymous> (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\oauth\\lib\\oauth2.js:157:7)\n    at IncomingMessage.emit (node:events:529:35)\n    at endReadableNT (node:internal/streams/readable:1400:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","status":500,"timestamp":"2025-05-09T14:55:14.196Z"}
{"level":"error","message":"Error fetching campaign history: Cannot populate path `communicationLogs` because it is not in your schema. Set the `strictPopulate` option to false to override.","path":"communicationLogs","stack":"StrictPopulateError: Cannot populate path `communicationLogs` because it is not in your schema. Set the `strictPopulate` option to false to override.\n    at getModelsMapForPopulate (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\helpers\\populate\\getModelsMapForPopulate.js:50:12)\n    at populate (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\model.js:4394:21)\n    at _populate (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\model.js:4354:5)\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\model.js:4326:5\n    at new Promise (<anonymous>)\n    at Function.populate (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\model.js:4325:10)\n    at model.Query._find (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\query.js:2320:20)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async model.Query.exec (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\query.js:4447:11)\n    at async exports.getCampaignHistory (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\controllers\\campaignController.js:28:23)","timestamp":"2025-05-09T16:03:01.499Z"}
{"level":"error","message":"Error fetching campaign history: Cannot populate path `communicationLogs` because it is not in your schema. Set the `strictPopulate` option to false to override.","path":"communicationLogs","stack":"StrictPopulateError: Cannot populate path `communicationLogs` because it is not in your schema. Set the `strictPopulate` option to false to override.\n    at getModelsMapForPopulate (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\helpers\\populate\\getModelsMapForPopulate.js:50:12)\n    at populate (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\model.js:4394:21)\n    at _populate (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\model.js:4354:5)\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\model.js:4326:5\n    at new Promise (<anonymous>)\n    at Function.populate (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\model.js:4325:10)\n    at model.Query._find (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\query.js:2320:20)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async model.Query.exec (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\query.js:4447:11)\n    at async exports.getCampaignHistory (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\controllers\\campaignController.js:28:23)","timestamp":"2025-05-09T16:06:35.642Z"}
{"level":"error","message":"Error fetching campaign history: Cannot populate path `communicationLogs` because it is not in your schema. Set the `strictPopulate` option to false to override.","path":"communicationLogs","stack":"StrictPopulateError: Cannot populate path `communicationLogs` because it is not in your schema. Set the `strictPopulate` option to false to override.\n    at getModelsMapForPopulate (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\helpers\\populate\\getModelsMapForPopulate.js:50:12)\n    at populate (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\model.js:4394:21)\n    at _populate (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\model.js:4354:5)\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\model.js:4326:5\n    at new Promise (<anonymous>)\n    at Function.populate (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\model.js:4325:10)\n    at model.Query._find (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\query.js:2320:20)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async model.Query.exec (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongoose\\lib\\query.js:4447:11)\n    at async exports.getCampaignHistory (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\controllers\\campaignController.js:28:23)","timestamp":"2025-05-09T16:07:14.686Z"}
{"level":"error","message":"Error fetching campaign history:","timestamp":"2025-05-09T18:05:34.381Z"}
{"level":"error","message":"Error fetching campaign history:","timestamp":"2025-05-09T18:05:42.741Z"}
{"level":"error","message":"Error fetching campaign history:","timestamp":"2025-05-09T18:10:49.649Z"}
{"level":"error","message":"Error fetching campaign history:","timestamp":"2025-05-09T18:11:07.400Z"}
{"level":"error","message":"Error fetching campaign history for user 681e16e5e9580d4eb804f09b: mongoose is not defined","timestamp":"2025-05-09T18:13:29.902Z"}
{"level":"error","message":"Error fetching campaign history:","timestamp":"2025-05-09T18:13:52.724Z"}
{"level":"error","message":"Error fetching campaign history for user 681e16e5e9580d4eb804f09b: mongoose is not defined","timestamp":"2025-05-09T18:14:34.271Z"}
{"level":"error","message":"Error fetching campaign history for user 681e16e5e9580d4eb804f09b: Class constructor ObjectId cannot be invoked without 'new'","timestamp":"2025-05-09T18:15:32.138Z"}
{"code":"invalid_grant","level":"error","message":"Authentication error: Bad Request","name":"TokenError","stack":"TokenError: Bad Request\n    at OAuth2Strategy.parseErrorResponse (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\passport-oauth2\\lib\\strategy.js:373:12)\n    at OAuth2Strategy._createOAuthError (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\passport-oauth2\\lib\\strategy.js:420:16)\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\passport-oauth2\\lib\\strategy.js:177:45\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\oauth\\lib\\oauth2.js:196:18\n    at passBackControl (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\oauth\\lib\\oauth2.js:132:9)\n    at IncomingMessage.<anonymous> (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\oauth\\lib\\oauth2.js:157:7)\n    at IncomingMessage.emit (node:events:529:35)\n    at endReadableNT (node:internal/streams/readable:1400:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","status":500,"timestamp":"2025-05-09T20:01:49.065Z"}
{"code":11000,"index":0,"keyPattern":{"email":1},"keyValue":{"email":"mohit@example.com"},"level":"error","message":"Error creating customer: E11000 duplicate key error collection: test.customers index: email_1 dup key: { email: \"mohit@example.com\" }","stack":"MongoServerError: E11000 duplicate key error collection: test.customers index: email_1 dup key: { email: \"mohit@example.com\" }\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongodb\\lib\\operations\\insert.js:50:33\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongodb\\lib\\operations\\command.js:84:64\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-09T20:05:33.808Z"}
{"level":"error","message":"Error sending message to mohit@example.com:","timestamp":"2025-05-10T19:55:39.736Z"}
{"level":"error","message":"Error sending message to mohit@examplae.com:","timestamp":"2025-05-10T19:55:39.744Z"}
{"level":"error","message":"Error sending message to taneja.garvit29@gmaile.com:","timestamp":"2025-05-10T19:55:39.747Z"}
{"level":"error","message":"Authentication error: C4700000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:c:\\ws\\deps\\openssl\\openssl\\ssl\\record\\rec_layer_s3.c:1605:SSL alert number 80\n","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":"7fffffff000000000000020e","maxSetVersion":209,"servers":{},"setName":"atlas-735ur2-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongoServerSelectionError: C4700000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:c:\\ws\\deps\\openssl\\openssl\\ssl\\record\\rec_layer_s3.c:1605:SSL alert number 80\n\n    at Timeout._onTimeout (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongodb\\lib\\sdam\\topology.js:278:38)\n    at listOnTimeout (node:internal/timers:569:17)\n    at process.processTimers (node:internal/timers:512:7)","timestamp":"2025-05-11T07:32:07.479Z"}
{"level":"error","message":"Authentication error: C4700000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:c:\\ws\\deps\\openssl\\openssl\\ssl\\record\\rec_layer_s3.c:1605:SSL alert number 80\n","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":"7fffffff000000000000020e","maxSetVersion":209,"servers":{},"setName":"atlas-735ur2-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongoServerSelectionError: C4700000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:c:\\ws\\deps\\openssl\\openssl\\ssl\\record\\rec_layer_s3.c:1605:SSL alert number 80\n\n    at Timeout._onTimeout (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongodb\\lib\\sdam\\topology.js:278:38)\n    at listOnTimeout (node:internal/timers:569:17)\n    at process.processTimers (node:internal/timers:512:7)","timestamp":"2025-05-11T07:33:07.997Z"}
{"code":"invalid_grant","level":"error","message":"Authentication error: Bad Request","name":"TokenError","stack":"TokenError: Bad Request\n    at OAuth2Strategy.parseErrorResponse (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\passport-oauth2\\lib\\strategy.js:373:12)\n    at OAuth2Strategy._createOAuthError (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\passport-oauth2\\lib\\strategy.js:420:16)\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\passport-oauth2\\lib\\strategy.js:177:45\n    at C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\oauth\\lib\\oauth2.js:196:18\n    at passBackControl (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\oauth\\lib\\oauth2.js:132:9)\n    at IncomingMessage.<anonymous> (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\oauth\\lib\\oauth2.js:157:7)\n    at IncomingMessage.emit (node:events:529:35)\n    at endReadableNT (node:internal/streams/readable:1400:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","status":500,"timestamp":"2025-05-11T07:34:23.194Z"}
{"level":"error","message":"Authentication error: C4700000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:c:\\ws\\deps\\openssl\\openssl\\ssl\\record\\rec_layer_s3.c:1605:SSL alert number 80\n","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":"7fffffff000000000000020e","maxSetVersion":209,"servers":{},"setName":"atlas-735ur2-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongoServerSelectionError: C4700000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:c:\\ws\\deps\\openssl\\openssl\\ssl\\record\\rec_layer_s3.c:1605:SSL alert number 80\n\n    at Timeout._onTimeout (C:\\Users\\tanej\\OneDrive\\Desktop\\crm\\backend\\node_modules\\mongodb\\lib\\sdam\\topology.js:278:38)\n    at listOnTimeout (node:internal/timers:569:17)\n    at process.processTimers (node:internal/timers:512:7)","timestamp":"2025-05-11T07:36:06.314Z"}
{"level":"error","message":"No user found in auth callback","timestamp":"2025-05-12T13:06:00.293Z"}
{"level":"error","message":"No user found in auth callback","timestamp":"2025-05-12T13:08:56.823Z"}
{"level":"error","message":"Error creating campaign for user 681e16e5e9580d4eb804f09b: Cast to Number failed for value \"{ gte: 5 }\" (type Object) at path \"visits\" for model \"Customer\"","timestamp":"2025-05-12T13:26:40.089Z"}
{"level":"error","message":"Error creating campaign for user 681e16e5e9580d4eb804f09b: Cast to Number failed for value \"{ gte: 1000 }\" (type Object) at path \"totalSpend\" for model \"Customer\"","timestamp":"2025-05-12T13:27:12.590Z"}
{"level":"error","message":"Error creating campaign for user 681e16e5e9580d4eb804f09b: Cast to Number failed for value \"{ gte: 5 }\" (type Object) at path \"visits\" for model \"Customer\"","timestamp":"2025-05-12T13:27:35.362Z"}
{"level":"error","message":"Error creating campaign for user 681e16e5e9580d4eb804f09b: Cast to Number failed for value \"{ gte: 1000 }\" (type Object) at path \"totalSpend\" for model \"Customer\"","timestamp":"2025-05-12T13:35:32.794Z"}
{"level":"error","message":"Error creating campaign for user 681e16e5e9580d4eb804f09b: Cast to Number failed for value \"{ gte: 1000 }\" (type Object) at path \"totalSpend\" for model \"Customer\"","timestamp":"2025-05-12T13:35:40.341Z"}
{"level":"error","message":"Error creating campaign for user 681e16e5e9580d4eb804f09b: Cast to Number failed for value \"{ gte: 1000 }\" (type Object) at path \"totalSpend\" for model \"Customer\"","timestamp":"2025-05-12T13:35:43.360Z"}
